name: release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string
      release_name:
        description: 'Release name (optional)'
        required: false
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Blender installation cache
        id: blender-cache
        uses: actions/cache@v4
        with:
          path: ./blender
          key: ${{ runner.os }}-blender-${{ hashFiles('./dev.py') }}
          restore-keys: |
            ${{ runner.os }}-blender-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build addon
        run: python dev.py build

      - name: Verify addon was built
        run: |
          if [ ! -f "NodeKit.zip" ]; then
            echo "Error: NodeKit.zip was not created"
            exit 1
          fi
          echo "NodeKit.zip created successfully"
          ls -la NodeKit.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name || inputs.tag_name }}
          files: NodeKit.zip
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
